configure.ac, eos/b-decays/b-to-d-l-nu.cc, eos/b-decays/b-to-d-l-x-nu.cc, eos/b-decays/b-to-pi-l-nu.cc, eos/b-decays/b-to-pi-l-x-nu.cc, eos/b-decays/b-to-pi-pi-l-nu.cc, eos/b-decays/bs-to-kstar-l-nu.cc, eos/form-factors/analytic-b-to-kstar.cc, eos/form-factors/analytic-b-to-pi-pi.cc, eos/form-factors/analytic-b-to-pi.cc, eos/form-factors/analytic-b-to-pi_TEST.cc, eos/rare-b-decays/bremsstrahlung.cc, eos/rare-b-decays/exclusive-b-to-s-dilepton-large-recoil.cc, eos/rare-b-decays/exclusive-b-to-s-dilepton-low-recoil.cc, eos/rare-b-decays/exclusive-b-to-s-dilepton-low-recoil_TEST.cc, eos/rare-b-decays/inclusive-b-to-s-dilepton.cc, eos/rare-b-decays/lambda-b-to-lambda-dilepton.cc, eos/utils/integrate-impl.hh, eos/utils/integrate.cc, eos/utils/integrate.hh, eos/utils/integrate_TEST.cc
This is to address #40 . It's not done yet but @dvandyk may review already. In particula, I'm happy about where to put what.
While implementing, I noticed that multithreading can be an issue. Right now the integration is thread safe if the integrand is. But every call to the adaptive integration reserves and frees memory. This memory could be shared if EOS is not used in multiple threads. Else one would need a pool of gsl_memory that one thread could reuse. These are performance issues that don't afffect correctness. Profiling a real use case will show if such compilcations are called for.
=> Move to GSL integration methods

eos/statistics/hierarchical-clustering.cc
This fixes two long-standing bug in the hierarchical clustering that are
cause by the following piece of code:
// update covariance
for (auto i = inverse_mapping[j].cbegin() ; i != inverse_mapping[j].cend() ; ++i)
{
[...]
// sigma = (mu'_j - mu_i) (mu'_j - mu_i)^T
gsl_blas_dsyr(CblasUpper, 1.0, mu_diff, sigma);
[...]
}
1. This accumulates the previous results in the variable sigma.
2. The 'dsyr' BLAS operation produces a symmetric matrix in
either upper or lower triangular shape. Since the result is
added to existing dense matrices, the triangular shape causes
severe asymmetries in some cases. This problem was exacerbated
in a setup that required the reduction of a larger number of
input components to a single output component.
Github: resolves #83
=> [statistics] Fix bugs in hierarchical clustering

eos/parameters/masses.yaml
Mistake on the max value of the s-quark mass(2GeV) is fixed. @dvandyk, please merge.
=> [parameters] Fix the default s-quark mass(2GeV)

configure.ac, eos/Makefile.am, eos/b-decays/Makefile.am, eos/form-factors/Makefile.am, eos/optimize/Makefile.am, eos/rare-b-decays/Makefile.am, eos/statistics/Makefile.am, eos/utils/Makefile.am, python/Makefile.am, src/clients/Makefile.am
I tried to compile the latest master with all dependencies in non-standard locations (and custom compiled boost). This lead to a variety of problems
* `boost_python_suffix` was not determined correctly
* abi flag was missing from python library (I only have `libpython3.6m`)
* GSL includes were not found as GSL was in non-standard location
* yaml-cpp was not found but the commit from pr #67 worked fine after rebasing
* missing `-lhdf5` leading to undefined reference
This pr fixes all of these issues for me but since I'm not an expert on the internal structure there might be better ways to do this.
=> [infra] Fix various problems with non-standard locations

configure.ac
On Ubuntu hdf5 can be installed in several flavours including an mpi
based and multhreaded one. We circumvent accidental linking against
hdf5-mpi by checking explicitly for hdf5-serial and falling back for
hdf5 otherwise.
=> [infra] Search first for hdf5-serial then hdf5

.travis/build-and-test.bash, configure.ac, debian/control-bionic.in, debian/control-xenial.in
1. The binary packages were missing a runtime dependency on ```libyaml-cpp0.5v5``` on both xenial and bionic.
2. Debian/Ubuntu do not use 'site-packages' for the installation of distribution-provided Python modules and extensions. Instead, they use 'dist-packages'. Changed the ```$(pythondir)``` and ```$(pyexecdir)``` variables on Debian/Ubuntu only.
=> Fix some bugs when installing in virgin Ubuntu installations

.travis.yml, .travis/build-and-test.bash, .travis/disco, configure.ac, debian/control-disco.in, doc/conf.py
At some point between 'bionic' and 'disco', Debian/Ubuntu have decided that their convention for the name of the ```libboost_python3-py37.so.${BOOST_VERSION}``` was stupid. So far, so good. In their unfathomable wisdom, they decided to replace it with ```libboost_python37.so.${BOOST_VERSION}```. So far, so bad.
@daritter Please be so kind to review the commit touching ```configure.ac```, to confirm that this will not break your Belle 2 Externals setup.
Fixes: #162
=> Fix issue #162: Provide .deb files for Ubuntu 'disco' (19.04)

eos/constraints/Lb-to-L-ll.yaml
Added an updated value for Lambda_b->Lambdall::BR@LowRecoil to Lb-to-L-ll.yaml using only TeVatron production information. Updates the LHCb 2015 branching fraction number.
=> Added updated Lb -> L mu mu BF number using only TeVatron normalisation

.travis.yml
TravisCI's ```xcode9.3``` consistently produces errors. Let's switch to a more recent XCode version.
=> [travis] Switch MacOSX testing image to use XCode 11

eos/b-decays/b-to-dstar-l-nu.cc, eos/b-decays/b-to-dstar-l-nu.hh, eos/b-decays/b-to-dstar-l-nu_TEST.cc, eos/b-decays/observables.cc, eos/signal-pdf.cc, python/eos/plot/plotter.py
This exports the q^2-differential and q^2-integrated angular observables in the J_i convention (J_i = 3/4 I_i). Some convenience changes are also included.
Github: resolves #209
=> Changes requested by Donal Hill

.github/workflows/macos-build+check.yaml, examples/cli/Makefile
Homebrew upgraded ```boost-python3``` to use Python version 3.9 now.
=> [github] Switch to Python 3.9 for builds on MacOS

python/eos/analysis.py
instead of using the default one in pympc
=> [python] Fix: pass the random number generator

eos/utils/parameters.cc
For the moment there are no tests on the deserialization of parameters, this PR may be the opportunity to add some.
Also, `boost/format` is currently not supported by C++20 which creates a conflict with issue #307.
=> Implement deserialization of templated parameters

eos/constraint.cc, eos/observable.cc, eos/observable.hh, eos/rare-b-decays/exclusive-b-to-s-dilepton-large-recoil.cc, eos/rare-b-decays/exclusive-b-to-s-dilepton-large-recoil.hh, eos/rare-b-decays/exclusive-b-to-s-dilepton-large-recoil_TEST.cc, eos/rare-b-decays/observables.cc
- R_K has two implementation; remove the specific one and keep the general one
- B->Kll observables use GSL::QNG, which fails to reach the needed precision in the q2 range 1.1 to 6.0 GeV^2; switch to GSL::QAGS
=> Fixes for Romy

configure.ac, eos/Makefile.am, eos/meson-mixing/Makefile.am, eos/meson-mixing/bq-mixing.cc, eos/meson-mixing/bq-mixing.hh, eos/meson-mixing/bq-mixing_TEST.cc, eos/meson-mixing/observables.cc, eos/meson-mixing/observables.hh, eos/observable.cc, eos/parameters/hadronic-matrix-elements.yaml, eos/parameters/sm-and-eft.yaml, eos/references.yaml, eos/utils/ckm_scan_model.cc, eos/utils/ckm_scan_model.hh, eos/utils/model.hh, eos/utils/qualified-name.cc, eos/utils/standard-model.cc, eos/utils/standard-model.hh, eos/utils/standard_model_TEST.cc, eos/utils/wilson_coefficients.cc, eos/utils/wilson_coefficients.hh, eos/utils/wilson_scan_model.cc, eos/utils/wilson_scan_model.hh, eos/utils/wilson_scan_model_TEST.cc, src/clients/Makefile.am
Available only for q=s at the moment, but readily extensible.
TODOs:
=> B_q <-> Bbar_q mixing

eos/b-decays/b-to-d-l-nu_TEST.cc, eos/b-decays/b-to-dstar-l-nu_TEST.cc, eos/b-decays/bs-to-kstar-l-nu_TEST.cc, eos/b-decays/lambdab-to-lambdac-l-nu_TEST.cc, eos/rare-b-decays/b-to-k-charmonium_TEST.cc, eos/rare-b-decays/b-to-k-ll-bfs2004_TEST.cc, eos/rare-b-decays/b-to-k-ll-gp2004_TEST.cc, eos/rare-b-decays/b-to-kstar-charmonium_TEST.cc, eos/rare-b-decays/b-to-kstar-gamma-bfs2004_TEST.cc, eos/rare-b-decays/b-to-kstar-ll-bfs2004_TEST.cc, eos/rare-b-decays/b-to-kstar-ll-gp2004_TEST.cc, eos/rare-b-decays/b-to-kstar-ll-gvdv2020_TEST.cc, eos/rare-b-decays/bs-to-phi-charmonium_TEST.cc, eos/rare-b-decays/bs-to-phi-ll-gvdv2020_TEST.cc, eos/rare-b-decays/exclusive-b-to-dilepton_TEST.cc, eos/rare-b-decays/inclusive-b-to-s-dilepton_TEST.cc, eos/rare-b-decays/inclusive-b-to-s-gamma_TEST.cc, eos/rare-b-decays/lambda-b-to-lambda-dilepton_TEST.cc, eos/utils/wilson_scan_model.cc, eos/utils/wilson_scan_model.hh
This commit fixes #313 by
The order of commits is such that the CKM matrix element are fixed first.
=> Fix issue #313

eos/utils/cartesian-product.hh
Including `<cstddef>` in the header of `utils/cartesian-product.hh` fixes a compiler error stating that `„size_t” was not declared`.
=> [utils] Include <cstddef> in cartesian-product.hh

doc/installation.rst
- Streamline the installation instructions
- most end-users will use the pip installation: now visible at first sight
- structure sections via specific use cases (OS -> installation method) instead of technical solution (Installation method -> platform specific)
- Change descriptions to action instead of intent (e.g. use `pip3` instead of PyPi); easier and more concrete
- Fix typos using a language tool
=> [doc] Improve several aspects

python/eos/analysis.py, python/eos/plot/plotter.py
This PR:
- Fixes a small bug in the labels of plotter.py
- Scales the sampler proposal back to the initial parameter space in pmc-sample
- Allows to fix a perplexity threshold to stop PMC adaptations
- Allows to return final step samples only in pmc-sample
=> Small python changes

python/eos/analysis.py
This commit yields so far undiagnosed occasional errors.
This reverts commit a948809167be0f7058c68d0f746259ccfba50d6e.
=> Revert "[python] Run up to 10 PMC adaptations per adaptation step"

.github/workflows/manylinux-build+check+deploy.yaml
libsatlas.so is a dependency of libgslcblas.so on the manylinux build image.
Re-add this library to the wheel.
=> [github] Fix missing library in PyPI wheel

eos/utils/parameters.cc, eos/utils/parameters.hh, eos/utils/parameters_TEST.cc, examples/cli/btopilnu.plot, python/Makefile.am, python/_eos.cc, python/eos/observable.py, python/eos/observable_TEST.py, python/eos/parameter.py, python/eos/parameter_TEST.py, python/eos/plot/plotter.py, python/eos/plot/plotter_TEST.py
Unify Plotter.Observable items 'kinematic' and 'parameter' to a single key 'variable' (which was also still implemented before as a proxy for 'kinematic'). This is a breaking change! We need to check and likely modify any documentation on this.
All changes are covered with unit tests, where test infrastructure was added where needed. Anticipated user errors are caught and reported with meaningful (expressive) error messages to improve the user experience.
=> Unify plot args

python/eos/signal_pdf.py
Although the tables were correctly rendered in a Jupyter notebook, exporting this notebook in PDF or displaying it in GitHub caused a rendering bugs with mixed cells.
=> [python] Fix the table representation of PDFs

doc/faq.rst, doc/installation.rst
Apart from the FAQ, I also noticed that the `pip` installation description can be shorter. Since this is our 'hero' installation method, I'd keep it as easy to grasp as possible.
I built the html doc to check the links and rendering.
---
- Add FAQ entry to troubleshoot problems with the module installation
- Shorten description of the pip3 installation
Solves #323
=> [doc] Improve installation documentation

doc/api/python.rst.jinja, doc/api/python.rst.py, doc/basics.rst, eos/b-decays/observables.cc, eos/rare-b-decays/inclusive-b-to-s-gamma.cc, eos/utils/thread_pool.cc, examples/inference.ipynb, python/eos/analysis_file.py, python/eos/data/pypmc.py, python/eos/plot/plotter.py, python/eos/tasks.py, src/scripts/eos-analysis
- tracks @cBobeth's commit from #423, fixing #236 
- fixes #424 
- documents all plot types used in the paper except for `histogram2D` and `kde2D`
- enables the perplexity threshold in the CLI script
- add means to continue a PMC sampling step, including further adaptations, from an existing `eos.data.PMCSampler` object
=> Another set of changes before v1.0

.github/workflows/macos-build+check.yaml, .github/workflows/manylinux-build+check+deploy.yaml, .github/workflows/ubuntu-build+check+deploy.yaml
When a PR is forced push, the previous workflow is automatically cancelled. This will avoid having queued jobs due to anyway useless failing jobs.
=> [github] Add concurrency in the jobs

python/eos/analysis.py, python/eos/data/pypmc.py, python/eos/tasks.py, src/scripts/eos-analysis
This PR:
- corrects a few typos
- Add a pruning of components with very small weights in `sample_pmc`
- Simplifies the default behavior for the computation of test statistics and implement it in the cli
=> A few changes in `sample_pmc`

src/clients/eos-print-polynomial.cc
I did a brief check on `B->D^*lnu::BR` that the coefficients of the Wilson coefficients become multiplied by a factor of 4 when  the value of `CKM::abs(V_cb)` is multiplied by factor of 2 for `model=WET`.
=> [clients] added option --parameter to commandline

python/eos/analysis.py, python/eos/ipython.py
In `sample_pmc`, components with very small weights can sometimes be so close to singular that they can't be rescaled. This commit catches the corresponding error and fix the weight of such components to 0
=> [python] Catch linalg error due to components that can't be rescaled

python/eos/analysis.py
eos.Analysis reports fixed_parameters as not being
part of the prior, issues info log message. Before
throwing the eos.info the fixed_parameters are now
subtracted from used_but_unvaried such that it does
include the fixed_parameters correctly.
=> [python] Avoid unnecessary log messages

.github/workflows/macos-build+check.yaml, configure.ac, doc/installation.rst, python/eos/analysis_file.py, python/eos/tasks.py, src/scripts/eos-analysis, src/scripts/eos-analysis_TEST, src/scripts/eos-analysis_TEST.d/analysis.yaml
(addresses discussion #432)
Each ``step`` requires a name, and a list of task descriptions. Optionally, it can provide a list of ``iterations``.
Similar to Github Action's ``strategy.matrix``, a step is run for each element of ``iterations``. In the example below,
the ``sample`` step is run twice: once for the posterior ``CKM-pi``, and once for the posterior ``CKM-rho``.
The example is correctly parsed and interpreted. It currently does not run the tasks. Instead, it prints the equivalent
``eos-analysis`` commands.
```yaml
steps:
- name: optimize
iterations:
- { posterior: CKM-all                                                         }
tasks:
- task: sample-mcmc
arguments:
posterior: 'CKM-all'
pre_N: 1000
- task: find-mode
arguments:
posterior: 'CKM-all'
- name: sample
iterations:
- { …
```
=> Provide a systematic framework to run analysis steps in a reproducible way

.github/workflows/manylinux-build+check+deploy.yaml, configure.ac
Probably does not need a review. Commits have been extracted from PR #521. Applying them later, due to our main workstations still running Ubuntu 18.04 LTS / Python 3.6.
=> Bump minimum Python version to >=3.7

eos/utils/gsl-hacks.cc, eos/utils/log.cc, eos/utils/memoise.hh, src/scripts/eos-analysis
- remove an unnecessary `const` type qualifier
- replace `std::uncaught_exception` with `std::uncaught_exceptions`
- mark an unused variable as unused in the GSL hacks
- only check verbosity in `eos-analysis` if a subcommand is invoked
=> Fix various warnings

python/eos/tasks.py, src/scripts/eos-analysis
The option to visualize marginalized posteriors using a corner plot as an `eos task` was added. A mistake from the previous implementation of the sample-nested task was corrected, namely the calculation of the samples so that they can be stored using `eos.data.ImportanceSamples`.
=> Corner plot and storing nested sampling results

python/eos/tasks.py
An optional 'format' input parameter was added, which may contain one string or a list of possible file extensions that specify how corner plots are stored. If left unspecified, it defaults to 'pdf'.
=> [python] Add format option for storage of corner plots

python/eos/analysis_TEST.py, python/eos/plot/plotter.py
=> [python] Use `numpy.double` instead of the decrepeted `numpy.float` and `numpy.float64`

eos/b-decays/b-to-3l-nu.cc, eos/b-decays/b-to-3l-nu_TEST.cc, eos/b-decays/observables.cc
I fixed a sign error in the implementation due to Q_B in equation 50 in 2210.09832, I forgot it.
Added new testcases.
Allowed for the observables to be evaluated with tauon flavour.
=> [b-decays] Fix sign error in [KKvDZ:2022A] and allow for tauon flavour

doc/api/python.rst.jinja
=> [doc] Fix typo in Python API documentation

eos/constraints/B-to-omega-l-nu.yaml, eos/utils/concrete-cacheable-observable.hh, eos/utils/concrete_observable.hh, eos/utils/expression-observable.cc, python/eos_TEST.py
- Adapt log level messaging for cases when when forcing option keys
- Remove option redundancy in `constraints\B-to-omega.yaml`
=> Adapt log level messaging, remove redundancy in constraint options

python/eos/analysis_file.py, src/scripts/eos-analysis_TEST.d/analysis.yaml
The syntax error in the loop initialization in `analysis_file.py` was fixed so that the parameters can be specified. A test was also added to `analysis.yaml` to check the modification.
=> Fix 'fixed_parameters' initialization for predictions

eos/constraint.cc, eos/constraint_TEST.cc
At some point we should implement response matrices in another constraint type.
Fixes #596
=> Painfully fix the `begin` and `end` options

eos/form-factors/observables.cc, eos/form-factors/parametric-bgl1997-impl.hh, eos/form-factors/parametric-bgl1997.cc, eos/form-factors/parametric-bgl1997.hh
Some of the BGL coefficients in our implementation are non-parametric, due to exact relations amongst the form factors at given phase space points. This PR
- turns the BGL form factor class into an ``ObservableProvider``;
- exports the pseudo observables for the ``a_0`` coefficients;
- fixes a bug in the naming of some pseudo observables for the coefficients of the HQE in B->D transitions.
Resolves #590.
=> Add pseudo observables for missing BGL coefficients 

.github/workflows/manylinux-build+check+deploy.yaml
Github is deprecating the ``ubuntu-18.04`` runner, which is currently still used by the PyPI workflow. Although a docker container is used, we need to update the runner.
=> Update actions runner to ``ubuntu-20.04`` for PyPI jobs

python/_eos.cc, python/eos/analysis_file.py
The small set of changes allows to use the expression parser to include custom observables in an analysis file.
=> Support observables from expressions in analysis file

eos/form-factors/b-lcdas-flvd2022.cc, eos/form-factors/b-lcdas-flvd2022.hh, eos/form-factors/b-lcdas-flvd2022_TEST.cc, eos/form-factors/observables.cc
The proposed changes allow to use the position space LCDA of the B meson $\tilde\phi_{B,+}(\tau)$ and its derivative as a constraint for the parametrisation introduced in `[FLvD:2022A]`. Such information can be extracted from theory through an operator product expansion.
=> Position space pseudo observable for ``b_lcdas::FLvD2022``

doc/installation.rst
The proposed changes list the `pip3` commands for installation and upgrade explicitly.
The user can find and copy the right command at a glance, which also better communicates the ease of this installation method.
Please find a preview attached.
=> [doc] Provide explicit table of common pip3 commands

.pre-commit-config.yaml
Hooks are kept in ``eos/pre-commit-hooks``.
=> Add EOS-specific pre-commit hooks

.github/workflows/ubuntu-build+check+deploy.yaml
The deployment step now only run if the workflow is triggered by a 'release' type event and if we are working on a tagged commit.
Github: resolves #640
=> Split build+deploy step for Ubuntu workflow

.github/workflows/manylinux-build+check+deploy.yaml, eos/constraint.cc, eos/constraint.hh, eos/statistics/Makefile.am, eos/statistics/goodness-of-fit.cc, eos/statistics/log-posterior.cc, eos/statistics/log-posterior.hh, eos/statistics/log-posterior_TEST.cc, eos/statistics/log-posterior_TEST.hh, eos/statistics/log-prior.cc, eos/statistics/log-prior.hh, eos/statistics/log-prior_TEST.cc, eos/utils/parameters.cc, eos/utils/parameters.hh, python/_eos.cc, python/eos/analysis.py, python/eos/analysis_TEST.py, python/eos/data/native.py, python/eos/tasks.py
This PR makes a few changes to the code base.
```
p.set_generator(u)
prior.sample()
p = prior.evaluate()
```
```
priors=[
{ 'constraint': 'foo->foo::bar@BAZ:2023A' },
{ 'parameter': 'mass::b(MSbar)', 'min': 4.15, 'max': 4.21, 'type': 'uniform' },
]
```
=> Increase efficiency of the ``sample-nested`` tasks through prior sampling

eos/utils/concrete_observable.hh, eos/utils/log.cc, eos/utils/observable_cache.cc, python/eos/__init__.py, python/eos_TEST.py
- do not log a warning when encountering a repeated forced option in ``Observable::make``; log an error if the forced option is overridden with a different value
- avoid logging to ``std::cerr`` by default
- avoid logging to ``sys.stderr`` in an interactive Python environment (i.e., Jupyter)
- fix typo when raising an ``InternalError`` in ``ObservableCache``.
Github: resolves #666
=> Fix warnings when repeating forced options upon Observable creation

eos/utils/Makefile.am, eos/utils/rge-impl.hh, eos/utils/rge.hh, eos/utils/rge_TEST.cc
=> Add generic classes for multiplicative RGE evolution up to NLL accuracy

eos/models/ckm.cc, eos/models/ckm.hh, eos/models/model.hh, eos/models/standard-model.cc, eos/models/standard-model.hh, eos/models/standard-model_TEST.cc, eos/models/wet.cc, eos/models/wet.hh, eos/models/wet_TEST.cc, eos/models/wilson-coefficients.hh, eos/parameters/sm-and-eft.yaml
Requires prior merging of #660.
Status:
=> Add tools for the qbcu sector of the WET

.pre-commit-config.yaml, doc/Makefile, doc/api/python.rst.jinja, doc/api/python.rst.py, python/Makefile.am, python/eos/figure/__init__.py, python/eos/figure/config.py, python/eos/figure/figure.py, python/eos/figure/item.py, python/eos/figure/plot.py
The proposed changes introduce a new submodule `eos.figure` to the python interface that should eventually replace the current `eos.plot`. As of now, the module is not feature-complete but can be used in addition/parallel to the existing one.
The changes facilitate a number of improvements:
- They create a clear separation of tasks. For instance, responsibilities like managing the appearance of a figure, generating data, and validating user input are handled separately.
- This separation enables automatic and comprehensive API documentation.
- It promotes consistent use of docstrings, unifying documentation and code within the same context to enhance maintainability of the documentation.
- Documentation and the Python `help()` function are unified, making both equally helpful.
- Overall …
=> New plotter

python/eos/tasks.py, src/scripts/eos-analysis
Allow the specification of indices to splice a corner plot.
=> [python] Add means to restrict range of parameters included in `corner-plot` task

.github/workflows/manylinux-build+check+deploy.yaml
Hi there, I think Python 3.11 wheels are created but not uploaded in the CD and are therefore also [missing in PyPI](https://pypi.org/project/eoshep/#files).
Just added the missing lines, AFAIU just a typo
=> Update CD for Python 3.11

python/Makefile.am, python/_eos.cc, python/_eos/external-log-likelihood-block.cc, python/_eos/external-log-likelihood-block.hh, python/_eos/log.cc, python/_eos/log.hh, python/_eos/version.cc, python/_eos/version.hh, python/_eos/wrappers.cc, python/_eos/wrappers.hh
- moved ``eos.version`` into separate files
- moved miscellaneous wrappers into separate files
- moved ``ExternalLogLikelihoodBlock`` into separate files
Github: resolves #689
=> Split ``_eos.cc`` into multiple files

eos/form-factors/analytic-b-to-gamma-qcdf.cc
Fixes a bug that causes warnings similar to
```
WARNING:EOS:likelihood does not depend on parameter 'B_u::a^phi+_1@FLvD2022'; remove from prior or check options!
```
=> [form-factors] Fix handling of B LCDA's parameter user

eos/utils/expression-cacher.hh, eos/utils/expression-cloner.hh, eos/utils/expression-evaluator.hh, eos/utils/expression-fwd.hh, eos/utils/expression-kinematic-reader.hh, eos/utils/expression-maker.hh, eos/utils/expression-parser-impl.hh, eos/utils/expression-parser.hh, eos/utils/expression-parser_TEST.cc, eos/utils/expression-printer.hh, eos/utils/expression-visitors.cc, eos/utils/expression.cc, eos/utils/expression.hh, eos/utils/qualified-name.cc
=> Expand ``ExpressionParser`` to handle undeclared parameters gracefully

eos/utils/expression-parser_TEST.cc, eos/utils/kmatrix_TEST.cc, eos/utils/parameters.cc, eos/utils/parameters.hh, eos/utils/parameters_TEST.cc, python/_eos.cc, python/eos/analysis_file.py, python/eos/pyhf_likelihood.py
Summary of change of functionality:
- default values are loaded at the first creation of a ``Parameter`` objects,
and stored in the ``ParameterDefaults`` singleton;
- ``Parameters::declare`` has become a static method returning ``void``;
- ``Parameters::decalare_and_insert`` has been added to facilitate declaring
a new parameter globally and inserting it into the current parameter set;
- test cases and Python interface have been adjusted.
Request review from @lorenzennio for changes to the handling of parameters in ``python/eos/pyhf_likelihood.py``.
=> Refactor parameters declare

doc/constraints.rst.py, doc/jinja_util.py, doc/observables.rst.py, doc/parameters.rst.py
Adding mangling for asterisks and carets in EOS QualifiedNames, which means the hyperlinks generated in the constraints list match the HTML id's in the parameters and observables list.
Also now checks if the links in the constraint page are to observables or parameters, and makes the link accordingly
Fixes #708
=> Fixes hyperlinks from constraints to observables/parameters

eos/rare-b-decays/b-to-vec-nu-nu.cc
I noticed that I have accidentally added a factor of 2 for the scalar and tensor Wilson coefficients, due to what is written in eq. 13 of https://arxiv.org/pdf/2111.04327.pdf. Later I noticed that the way we implemented eq. 8 in 
https://github.com/eos/eos/blob/4328b6320282b0543ceecfb6715a50eb6a9e102d/eos/rare-b-decays/b-to-psd-nu-nu.cc#L193-L198
I should not have added factors of 2 here. Sorry about that!
=> [rare-b-decays] Fix inconsistency in Wilson coefficient interpretation

eos/form-factors/k-lcdas.cc, eos/form-factors/k-lcdas.hh, eos/form-factors/pi-lcdas.cc, eos/form-factors/pi-lcdas.hh, eos/observable_TEST.cc, python/eos/tasks.py, src/scripts/eos-analysis
Merges the following changes:
- use ``analysis.yaml`` instead of the (hidden) ``.analysis.yaml`` as the default name for an analysis files in ``eos-analysis``
- run ``pyupgrade`` on ``python/eos/tasks.py``
- provide means to specify optional required modules for every task (#693)
- add a new subcommand ``eos-analysis init``, which install the contents of [eos/analysis-template](https://github.com/eos/analysis-template) into the current working directory
- check the names of kinematic variables in all observables against a whitelist (#750)
- improve the usage of ``GegenbauerPolynomial`` in classes ``PionLCDAs``, ``AntiKaonLCDAs``, and ``KaonLCDAs`` (in furtherance of addressing #747)
=> Changes for master

eos/utils/Makefile.am, eos/utils/expression-observable.cc, eos/utils/expression-parser_TEST.cc, eos/utils/expression-used-parameter-reader.hh, eos/utils/expression-visitors.cc, python/eos/plot/plotter.py
- When plotting a constraint, we currently produce an ungraceful Python exception if the plot contains no data points whatsoever.
This problem, for example, happens if you plot ``process::observable1`` but the constraint does not contain that observable. Practically, this happened in one of my Jupyter notebooks, where I used the same code to create plots for all ``B->D^*`` form factors, but one constraint did not provide information on the tensor form factors.
The user will now be informed of this issue through the logfile and the plotting will continue w/o the use of the constraint at issue.
- When creating an expression observable, it should keep track of the parameters used by the expression and provided through the observable's ``ParameterUser`` interface. This is now done, using a …
=> Changes for ``master``

.github/actions/report-activity/action.yml, .github/actions/report-activity/index.js, .github/actions/report-activity/package.json, .github/actions/report-activity/template.md, .github/workflows/pypi-build+check+deploy.yaml, .github/workflows/report-activity.yaml, .github/workflows/ubuntu-build+check+deploy.yaml
=> Various workflow related changes

eos/b-decays/lambdab-to-lambdac2595-l-nu.cc, eos/b-decays/lambdab-to-lambdac2625-l-nu.cc, eos/b-decays/observables.cc, eos/observable_TEST.cc
Some observables used ``theta_l`` to denote $\cos(\theta_\ell)$. This PR fixes this issue:
=> Fix issue 766

.github/workflows/pre-commit.yaml
This should remove the warning from github workflow.
=> [github] Specify the python version in the pre-commit workflow

doc/reference/analysis-file-format.rst, doc/user-guide/b-to-u-l-nu.yaml, eos/utils/parameters.cc, eos/utils/parameters.hh, eos/utils/parameters_TEST.cc, examples/Makefile, examples/analysis-organisation.ipynb, python/_eos.cc, python/eos/analysis_file.py, src/scripts/eos-analysis_TEST.d/analysis.yaml
This PR implements suggestion 4 of issue #801, following feedback from @smeiser and @MJKirk.
Example code for an analysis file:
```yaml
parameters:
'ublnul::Re{cVL}' :
alias_of: [ 'ubenue::Re{cVL}', 'ubmunumu::Re{cVL}', 'ubtaunutau::Re{cVL}' ]
central: +1.0
min:     +0.0
max:     +2.0
unit:     '1'
latex:    '$\mathrm{Re}\, \mathcal{C}^{\bar{u}b\bar{\ell}\nu_\ell}_{V_L}$'
```
=> Add means to alias parameters

.github/workflows/pre-commit.yaml, .github/workflows/pypi-build+check+deploy.yaml, .github/workflows/ubuntu-build+check+deploy.yaml
As discussed at a recent developer meeting, we will change our release procedure to decrease the number of development release to PyPI.
1. We will continue to push changes to ``master`` via pull requests. Pull request will need passing checks and approval. We will no longer produce (pre)release PyPI wheel or packagecloud .deb files from ``master``.
2. We will periodically push from ``master`` to ``release``. The new branch already exists and a branch protection has been setup. Every push to ``release`` will produce either a prerelease PyPI wheel + documentation; or produce a full release PyPI wheel + documentation + packagecloud .deb file.
=> Changes to the release procedure

doc/.gitignore, doc/jinja_util.py, doc/reference/command-line-interface.rst, eos/references.yaml, python/_eos.cc, python/eos/analysis.py, python/eos/observable.py, python/eos/parameter.py, python/eos/plot/plotter.py, python/eos/signal_pdf.py
In the process of solving #805 I found more links in the rest of the documentation that were "broken".
I say "broken", since most of these actually work on the live documentation but take you to the wrong place. For example go to https://eos.github.io/doc/reference/python.html#eos.Analysis and click the link for the "complete list of constraints" - you'll find yourself on the page for the constraints in EOS v1.0.10 not 1.0.11!
This is because when Danny reorganised the documentation, the pages got added to their new locations in the [eos/doc](https://github.com/eos/doc/) repo but the old ones were not removed.
=> Fixes various broken links in documentation

.github/workflows/pypi-build+check+deploy.yaml, .pre-commit-config.yaml, configure.ac, python/setup.py.in
=> Bump minimal Python version to 3.9

python/eos/analysis_file.py, python/eos/analysis_file_description.py
=> Allow specifying options to a prediction observable in an AnalysisFile

.github/workflows/weekly-builds.yaml
Essentially, replace
```
git push origin origin/master:release
```
with
```
git push origin $(git rev-parse origin/master):release
```
The latter works. The former doesn't. The mind is boggled.
=> Fix the ``git push`` command in the weekly release workflow

doc/user-guide/predictions.yaml, eos/b-decays/observables.cc, examples/predictions.ipynb, examples/predictions.yaml, python/eos/analysis.py, python/eos/analysis_file.py, python/eos/analysis_file_description.py, python/eos/tasks.py
=> Rewrite example notebook on theory predictions

eos/b-decays/bq-to-dq-psd.cc, eos/b-decays/bq-to-dq-psd_TEST.cc, eos/b-decays/bq-to-dstarq-psd.cc, eos/b-decays/bq-to-dstarq-psd_TEST.cc
- Changed the K LCDA used from "K" to "Kbar
- Added minus sign to the three-particle hard-scattering kernel for the TLL structure
- Added the LCDA parameters in the test cases to avoid usage of default values
- Updated values for test cases
=> Fix bugs in B_s -> D_s^(*) Pi and B -> D^(*) K ampitudes

.github/CODEOWNERS, eos/utils/options.hh, python/eos/tasks.py
=> Miscellaneous changes

.github/workflows/weekly-builds.yaml
=> Next attempt at fixing the ``weekly-builds`` workflow

eos/constraints/Makefile.am
- Add Bq-to-Dq-P constraints to constraint Makefile, which in a previous version was forgotten
=> [constraints] Add Bq-to-Dq-P constraints to constraint Makefile

src/scripts/Makefile.am, src/scripts/eos-list-observables, src/scripts/eos-list-references
Since I deleted the old ``eos-list-observables`` CLI program, let me at least add a basic script doing the same job.
=> Add a basic ``eos-list-observables`` script

eos/maths/szego-polynomial.hh
The warning caused in FlatMeasure in szego-polynomial.hh is caused by one faulty comparison.
Comparing with literature, e.g. the paragraph below Eq. B.6 in [https://arxiv.org/abs/2305.06301](2305.06301), shows that i (k in 2305.06301) is smaller than the order, not smaller or equal.
=> [maths] Fix undefined behaviour in FlatMeasure.

python/eos/tasks.py
=> [python] Fix errors for mutually incompatible options in find_modes

eos/b-decays/bq-to-dq-psd_TEST.cc, eos/b-decays/bq-to-dstarq-psd_TEST.cc, eos/form-factors/k-lcdas.cc, eos/form-factors/k-lcdas_TEST.cc, eos/parameters/hadron-properties.yaml
Currently we have eq. 4.19 of https://arxiv.org/pdf/hep-ph/0603063 implemented, with kappa4(mu0) as a parameter. However, kappa_4(mu0) is fixed by eq. 4.18. Thus having kappa4(mu0) as a parameter can lead to inconsistent input, that would violate eq. 4.18. Therefore, I propose to remove kappa4_0 as a parameter and rather just plug in the expression given in 4.18 into 4.19. This ensures that there are no inconsistencies. However, this now breaks a number of test cases that have to be adjusted.
=> Fix inconsistent definition of kappa_4 parameter appearing in twist 4 Kaon LCDAs

eos/observable.cc, eos/observable.hh, eos/observable_TEST.cc, examples/pyhf_corr.yaml, examples/pyhf_example.ipynb, examples/pyhf_uncorr.yaml, python/_eos.cc, python/eos/analysis_TEST.d/analysis_file_pyhf.yaml, python/eos/analysis_TEST.py, python/eos/pyhf_likelihood.py
Add a pyhf example (see #807).
TODOs:
return xlogy(n, lam) - lam - gammaln(n + 1.0)  # type: ignore[no-any-return]```
=> [examples] add pyhf example notebook

eos/constraint.cc, eos/reference.cc, eos/utils/parameters.cc
In Boost 1.86, some headers are not included through boost/filesystem/operations.hpp anymore and need to be explicitly included. This pull request adds the respective headers in the three affected files.
=> Make EOS compile with Boost 1.86

python/eos/data/native.py, python/eos/datasets.py, python/eos/datasets_file_description.py
Requires merging of PR #968 first.
=> Add initial support to load nabu-based likelihoods

eos/utils/expression-cacher.hh, eos/utils/expression-cloner.hh, eos/utils/expression-evaluator.hh, eos/utils/expression-fwd.hh, eos/utils/expression-kinematic-reader.hh, eos/utils/expression-maker.hh, eos/utils/expression-parser-impl.hh, eos/utils/expression-parser.hh, eos/utils/expression-parser_TEST.cc, eos/utils/expression-printer.hh, eos/utils/expression-used-parameter-reader.hh, eos/utils/expression-visitors.cc, eos/utils/expression.cc, eos/utils/expression.hh
=> Add support for calling a limited set of builtin unary functions within an expression

.github/workflows/pypi-build+check+deploy.yaml
... and save @dvandyk about 20 quid per month :wink:
It seems to be working:
=> Switch to free Github-hosted aarch64 runners

eos/statistics/log-prior.cc, eos/statistics/log-prior.hh
=> Rewrite ``prior::Transform`` to use LU decomposition

.github/workflows/pypi-build+check+deploy.yaml, .github/workflows/report-activity.yaml, .github/workflows/ubuntu-build+check+deploy.yaml, .github/workflows/weekly-builds.yaml
Given the recent warning that
```
[t]he Ubuntu 20.04 runner image will be fully unsupported by April 1, 2025[,]
```
let's move things to Ubuntu 24.04!
This affects
- the PyPI ``build+check+deploy`` workflow,
- the Ubuntu ``build+check+deploy`` workflow,
- the ``weekly-builds`` workflow, and
- the ``report-activity`` workflow.
For the first two, only the runner's image will be updated. The last two should not depend on the runner image version.
=> Move Ubuntu-based workflows to 24.04

python/eos/analysis.py, python/eos/analysis_file_description.py, python/eos/tasks.py
=> Improvement to the ``sample-nested`` user interface

eos/form-factors/mesonic.cc, eos/form-factors/observables.cc, eos/form-factors/parametric-bgl1997-impl.hh, eos/form-factors/parametric-bgl1997.cc, eos/form-factors/parametric-bgl1997.hh, eos/form-factors/parametric-bgl1997_TEST.cc, eos/parameters/hadronic-matrix-elements.yaml
Fixes #974: It is now possible to dynamically set the resonance masses and susceptibilities of the BGL parametrization to a specific value.
=> Un-hardcoded susceptibilities and resonance masses in BGL parametrization

.pre-commit-config.yaml, eos/nonleptonic-amplitudes/nonleptonic-amplitudes-adapter.hh, eos/nonleptonic-amplitudes/nonleptonic-amplitudes-fwd.hh, eos/nonleptonic-amplitudes/nonleptonic-amplitudes.cc, eos/nonleptonic-amplitudes/nonleptonic-amplitudes.hh, eos/nonleptonic-amplitudes/observables.cc, eos/nonleptonic-amplitudes/qcdf-amplitudes.cc, eos/nonleptonic-amplitudes/qcdf-amplitudes.hh, eos/nonleptonic-amplitudes/qcdf-amplitudes_TEST.cc, eos/nonleptonic-amplitudes/su3f-amplitudes.cc, eos/nonleptonic-amplitudes/su3f-amplitudes.hh, eos/nonleptonic-amplitudes/su3f-amplitudes_TEST.cc, eos/nonleptonic-amplitudes/topological-amplitudes.cc, eos/nonleptonic-amplitudes/topological-amplitudes.hh, eos/nonleptonic-amplitudes/topological-amplitudes_TEST.cc
I had to exclude the matrix definition in eos/nonleptonic-amplitudes/nonleptonic-amplitudes.cc as the clang format made no sense.
=> Clean up nonleptonic amplitudes

eos/nonlocal-form-factors/charm-loops-analytic_TEST.cc
This test seems to fail when compiling on ws16, so slightly increase the tolerance
=> [nonlocal-form-factors] Increase tolerance in test

eos/maths/omnes-factor-impl.hh, eos/maths/omnes-factor.hh, eos/maths/omnes-factor_TEST.cc
Currently we throw an exception when delta is near Pi/2 when evaluating the Omnes factor. However, this does not get passed through to observables etc. and can cause issues in numerical integration. For the fix we Taylor-expand the product of absolute values and the tangent of the phase near Pi/2 which is finite.
=> Evaluation of Omnes factor near delta = Pi/2

doc/reference/analysis-file-format.rst, python/eos/analysis_file.py, python/eos/analysis_file_description.py, python/eos/data/native.py, python/eos/tasks.py, src/scripts/eos-analysis
A minimum working example here -- for now, can only filter based on a set of observables from a Prediction part of an analysis file, and the resulting mask can be applied to `predict-observables`.
The mask reading and writing should almost certainly be split off into a new class in eos/data/native, I just couldn't be bothered to do it yet.
This draft PR is just to allow some discussion of the details.
In terms of defining the observables, I see three potential options:
1. Give a comma separated list on the command line, e.g. `--filter-obs=0->pipi::Arg{f_+}(q2);I=1;q2=0.5,0->pipi::Arg{f_+}(q2);I=1;q2=1`
2. Re-use the `predictions` section of the analysis file, as done here
3. Add a new `filtering-obs` section, which is essentially a copy of the predictions section
4. 
My preference would …
=> Filter samples task

.github/workflows/pypi-build+check+deploy.yaml
- update to EOS manylinux_2_28 build images with tag 2025-05-19-95bbb72
- update pyp/cibuildwheel action to v2.23.3
- start building the x86_64 wheels for Python version 3.13
- start building the aarch64 wheels for Python version 3.12 & 3.13
GitHub: resolves #1014
=> Update build images for PyPI workflow and start building for Python 3.13

python/eos/__init__.py, python/eos/tasks.py, src/scripts/eos-analysis
- Log messages are saved to a task's log file, using log level ``DEBUG``.
- Log messages are output to standard error, using log level ``INFO``.
- If running in eos-analysis, log messages to standard error start only at level ERROR. Appending ``--verbose``/``-v`` to the command line increase this log level up to ``DEBUG``.
@mreboud Let me know if you are happy with this, and please check it with your notebooks.
=> Improve handling of log messages across tasks, notebook, and the eos-analysis script

python/eos/analysis_file.py, python/eos/analysis_file_TEST.d/minimal-analysis-file.yaml, python/eos/analysis_file_TEST.py
`_predictions` needs to be a dict, not a list, otherwise the validation code here 
https://github.com/eos/eos/blob/67f63cd6d7a64163e1b02bb6d70284d0d907254e/python/eos/analysis_file.py#L323
fails if the analysis file has no predictions.
=> [python] Fix bug in `AnalysisFile` internals
