- eos/utils/hdf5.cc
> Replace throwing exceptions in HDF5 handle dtors with logging error messages

- .travis/build-and-test.bash
- python/eos/data/__init__.py
- python/eos/plot/plotter.py
- python/eos_TEST.py
- src/scripts/eos-plot
> Python logging

- .gitignore
- eos/b-decays/Makefile.am
- eos/b-decays/lambdab-to-lambdac2595-l-nu.cc
- eos/b-decays/lambdab-to-lambdac2595-l-nu.hh
- eos/b-decays/lambdab-to-lambdac2595-l-nu_TEST.cc
- eos/b-decays/lambdab-to-lambdac2625-l-nu.cc
- eos/b-decays/lambdab-to-lambdac2625-l-nu.hh
- eos/b-decays/lambdab-to-lambdac2625-l-nu_TEST.cc
- eos/form-factors/Makefile.am
- eos/form-factors/baryonic-impl.hh
- eos/form-factors/baryonic.cc
- eos/form-factors/baryonic.hh
- eos/form-factors/baryonic_TEST.cc
- eos/form-factors/hqet-b-to-c.cc
- eos/form-factors/hqet-b-to-c.hh
- eos/form-factors/hqet-b-to-c_TEST.cc
- eos/form-factors/zero-recoil-sum-rule.cc
- eos/form-factors/zero-recoil-sum-rule.hh
- eos/observable.cc
- eos/parameters/form-factors.yaml
- eos/parameters/masses.yaml
- eos/references.yaml
- eos/signal-pdf.cc
- eos/utils/qualified-name.cc
- python/eos/data/__init__.py
- src/clients/.gitignore
- src/clients/eos-sample-events-mcmc.cc
- src/scripts/.gitignore
Based on [this paper](https://arxiv.org/abs/1801.08367). Replaces PR #74. Notifying @elgicse, since she's not (yet?) a project member.
> Merge code from the Lb->Lc*lnu paper

- eos/utils/parameters.cc
- eos/utils/parameters.hh
- examples/b-to-tau-nu-uncertainty.ipynb
- python/Makefile.am
- python/_eos.cc
- python/eos/__init__.py
- python/eos/ipython.py
- python/eos/plot/config.py
@fredRos Have a look [here](https://github.com/dvandyk/eos/blob/6c8d2baccfa3584e201ddb6bfe4e6795e6182be2/examples/jupyter-uncertainty.ipynb) for a display of the notebook.
> Begin Jupyter integration

- eos/references.yaml
- manual/examples/btopilnu.plot
- python/_eos.cc
- python/eos/data/__init__.py
- python/eos/plot/plotter.py
- src/scripts/eos-list-references.in
- src/scripts/eos-plot-1d
- src/scripts/eos-plot-2d
- plot watermarks
- YAMLize references
- fix eos-list-references
- allow for searching references when using eos-list-references
> Various changes

- eos/b-decays/lambdab-to-lambdac2595-l-nu_TEST.cc
- eos/b-decays/lambdab-to-lambdac2625-l-nu_TEST.cc
- eos/form-factors/baryonic-impl.hh
- eos/form-factors/baryonic_TEST.cc
@elgicse Here's the PR with the changes Marzia and I just plugged in. Please have a look.
> [form-factors] Fix bug at subleading power in HQET results for Lambda_b->Lambda_c^* form factors

- configure.ac
- eos/statistics/markov-chain-sampler.hh
- manual/doc/usage.tex
- src/scripts/Makefile.am
- src/scripts/eos-merge-mcmc
First working version from uncluttering `merge.py` from the old eos scripts repo
fixes #28
> [scripts] Add eos-merge-mcmc

- eos/statistics/markov-chain-sampler.cc
- eos/statistics/markov-chain-sampler.hh
- manual/doc/usage.tex
- src/clients/eos-propagate-uncertainty.cc
- src/scripts/eos-merge-mcmc
> propagate uncertainty to use MCMC samples

- eos/references.yaml
- manual/doc/extending.tex
- manual/doc/installation.tex
- manual/doc/usage.tex
- manual/examples/x-constraints.yaml
- manual/manual.tex.in
- manual/physics/eft.tex
- manual/references.bib
- clean up old references to ```eosdata```
- add reference to the Amoroso paper
- add 'How to add a new constraint' to the manual
@greenwald Once you accept the invitation I can assign you as a reviewer.
> Changes to the manual

- eos/b-decays/b-to-d-l-nu.cc
- eos/b-decays/b-to-dstar-l-nu.cc
- eos/b-decays/b-to-dstar-l-nu.hh
- eos/b-decays/b-to-dstar-l-nu_TEST.cc
- eos/observable.cc
@dvandyk and @cBobeth can you please review this PR, cheers.
> Generic NP contribution to B->D^*lnu including tensor operators effects

- eos/b-decays/b-to-dstar-l-nu.cc
- eos/b-decays/b-to-dstar-l-nu.hh
- eos/b-decays/b-to-dstar-l-nu_TEST.cc
- eos/observable.cc
- eos/signal-pdf.cc
@cBobeth could you please review this PR? cheers.
> Full angular distribution for B->D^*lnu

- eos/b-decays/b-to-d-l-nu.cc
- eos/b-decays/b-to-d-l-nu.hh
- eos/b-decays/b-to-d-l-nu_TEST.cc
- eos/observable.cc
- eos/signal-pdf.cc
@cBobeth could you please review this pull request, cheers.
> Two-fold distribution for B->D l nu

- .travis.yml
- .travis/build-and-test.bash
Necessary, since our previous 'test' job exceeded the 50min time limit per job imposed by TravisCI for public Github repos.
> [travis] Split 'test' job into 'distcheck' and 'deploy' jobs

- python/eos/data/__init__.py
- src/scripts/Makefile.am
- src/scripts/eos-print-modes
@SKuerten Does this work for you?
Fixes: #167
> Fix issue #167: Add eos-print-modes script

- src/clients/Makefile.am
> [infra] Fix missing hdf5 dependency

- eos/b-decays/b-to-d-l-nu_TEST.cc
- eos/b-decays/b-to-psd-l-nu.cc
- eos/b-decays/b-to-psd-l-nu.hh
- eos/references.yaml
-> lepton polarization (lepton spin asymmetry)
! Changed sign in definition to match Belle measurement
-> added observable "flat term" known from B->K ll
Github: resolves #195
> [b-decays] Complete missing new physics contribution to observables

- eos/b-decays/b-to-d-l-x-nu.cc
- eos/b-decays/b-to-d-l-x-nu.hh
- eos/b-decays/b-to-pi-l-x-nu.cc
- eos/b-decays/b-to-pi-l-x-nu.hh
- eos/b-decays/b-to-psd-l-nu.cc
- eos/b-decays/b-to-psd-l-nu.hh
- eos/signal-pdf.cc
- eos/signal-pdf.hh
- eos/utils/concrete-signal-pdf.hh
Rewriting SignalPDF to disentangle the pdf and its normalization.
> [eos] Rewriting SignalPDF and companion classes

- eos/constraint.cc
- eos/constraint_TEST.cc
- eos/statistics/log-likelihood.cc
- eos/statistics/log-likelihood.hh
Modifications produced together with Chrístoph Bobeth.
GitHub: resolves #175
> Prepare MultivariateGaussianConstraint to accept a response matrix for folded data

- eos/constraint.cc
- eos/constraint.hh
- eos/form-factors/analytic-b-to-pi.cc
- eos/form-factors/analytic-b-to-pi.hh
- eos/form-factors/analytic-b-to-pi_TEST.cc
- eos/form-factors/observables.cc
- eos/parameters/hadron-properties.yaml
- eos/parameters/hadronic-matrix-elements.yaml
- eos/parameters/sm-and-eft.yaml
- python/_eos.cc
- python/eos/__init__.py
- python/eos/analysis.py
- python/eos/analysis_file.py
- python/eos/data/hdf5.py
- python/eos/data/pypmc.py
- python/eos/plot/plotter.py
- src/scripts/eos-analysis
- src/scripts/eos-analysis_TEST.d/analysis.yaml
Includes some major additions to the python-based CLI (eos-analysis).
> Changes related to issue #196

- eos/statistics/markov-chain-sampler.cc
- eos/statistics/markov-chain-sampler_TEST.cc
- eos/utils/observable_cache.cc
- src/clients/eos-sample-events-mcmc.cc
- src/clients/eos-sample-mcmc.cc
- src/clients/eos-scan-mc.cc
> [utils] Add multithreading support to ObservableCache

- python/eos/plot/config.py
Use single string for pgf.preamble instead of list
> [python] Fix MatplotlibDeprecationWarning

- eos/b-decays/lambdab-to-lambdac-l-nu_TEST.cc
- eos/form-factors/analytic-b-to-pi-pi.cc
- eos/form-factors/analytic-b-to-pi-pi_TEST.cc
- eos/parameters/hadron-properties.yaml
- eos/rare-b-decays/exclusive-b-to-s-dilepton-low-recoil_TEST.cc
- eos/rare-b-decays/exclusive-b-to-s-gamma_TEST.cc
- eos/rare-b-decays/lambda-b-to-lambda-dilepton_TEST.cc
> [parameters] Update masses and add latex names for masses

- eos/constraint.cc
- eos/constraint_TEST.cc
> Add an option to the MultivariateGaussian class to run on a restricted number of measurments

- doc/use-cases.rst
> [doc] Correct typo

- debian/control-bionic.in
- debian/control-disco.in
- debian/control-focal.in
- debian/control-xenial.in
- doc/installation.rst
> Remove Minuit2 from the documentation

- doc/api/python.rst
- eos/signal-pdf.cc
- eos/signal-pdf.hh
- eos/utils/parameters.cc
- python/Makefile.am
- python/_eos.cc
- python/eos/__init__.py
- python/eos/plot/plotter.py
- python/eos/signal_pdf.py
- src/clients/eos-list-signal-pdfs.cc
Changes in preparation for @KDugic's project.
> Make SignalPDF usable in python

- eos/references.yaml
- eos/utils/Makefile.am
- eos/utils/kmatrix-impl.hh
- eos/utils/kmatrix.hh
- eos/utils/kmatrix_TEST.cc
> Add an implementation of the K matrix formalism for the study of scattering processes

- python/eos/plot/plotter.py
@mreboud Could you please check my logic to compute the ellipses?
> [python] Add new plot type: 'constraint2D'

- eos/constraint.cc
- eos/constraint.hh
- eos/utils/kinematic.cc
- eos/utils/kinematic.hh
- python/_eos.cc
- add ``operator+`` for ``Kinematics``
- add means to insert or overwrite a ``ConstraintEntry`` at runtime
- export ``Observable::parameters()``
> Various changes for master

- eos/parameters/hadronic-matrix-elements.yaml
- eos/parameters/sm-and-eft.yaml
> [parameters] Fix more LaTeX representations

- eos/parameters/hadronic-matrix-elements.yaml
- eos/parameters/sm-and-eft.yaml
> [parameters] Change operatorname to mathrm

- src/scripts/eos-analysis
This is done using the '--from-point 'POINT AS STRING' option
> [eos-analysis] Add option to initialise 'find-point' from a given parameter point

- python/eos/analysis.py
These changes have no impact for the user. This scaling improves the convergence of `analysis.optimize`.
> [python] Internally scale analysis parameters to [-1, 1] for better interface with other softwares

- python/eos/analysis.py
It doesn't really look like pretty code... Any suggestion?
> [python] Correct issue related to yaml.dump and numpy types

- python/eos/analysis.py
I tested this locally, should we think about a test case for this?
Closes #336.
> [python] Sanitize the weights in the computations of the perplexity

- doc/basics.rst
- doc/index.rst
- doc/use-cases.rst
Add basics to the online documentation
> [doc] Add basics fix typo in use-cases

- python/Makefile.am
- python/eos/analysis.py
- python/eos/analysis_TEST.py
This PR adds the possibility to write tests for Python implementations.
> Python tests

- eos/Makefile.am
- eos/observable.cc
- eos/observable.hh
- eos/observable_TEST.cc
- eos/utils/Makefile.am
- eos/utils/exception.cc
- eos/utils/exception.hh
- eos/utils/expression-fwd.hh
- eos/utils/expression-observable.cc
- eos/utils/expression-observable.hh
- eos/utils/expression-parser-impl.hh
- eos/utils/expression-parser.hh
- eos/utils/expression-parser_TEST.cc
- eos/utils/expression-visitors.cc
- eos/utils/expression.cc
- eos/utils/expression.hh
- eos/utils/kinematic.cc
- eos/utils/kinematic.hh
- eos/utils/kinematic_TEST.cc
- eos/utils/one-of.hh
- eos/utils/qualified-name.cc
- eos/utils/qualified-name.hh
- eos/utils/qualified-name_TEST.cc
- python/_eos.cc
This is still preliminary work since Kinematics are not yet fully implemented.
> [utils] Add a preliminary expression parser in eos and its test.

- doc/observables.rst.py
- python/_eos.cc
- python/eos/observable.py
Add a representation of an observables unit to the Jupyter output and documentation.
> Display unit

- doc/observables.rst.py
- eos/form-factors/form-factor-adapter.hh
- eos/observable.cc
- eos/observable.hh
- eos/observable_TEST.cc
- eos/utils/concrete-cacheable-observable.hh
- eos/utils/concrete_observable.hh
- eos/utils/expression-observable.hh
- eos/utils/units.cc
- eos/utils/units.hh
- python/_eos.cc
Fixes the last item of #359, namely the Units.
> Units for expression observables

- doc/observables.rst.py
- python/_eos.cc
A direct fix on top of the previous commit. I suggest to squash them.
> [doc] Fix broken doc/observables, unit handling

- eos/utils/concrete-cacheable-observable.hh
- eos/utils/concrete_observable.hh
- eos/utils/expression-observable.cc
- eos/utils/options_TEST.cc
- eos/utils/qualified-name.cc
- eos/utils/qualified-name.hh
@DomLeljak this commit fixed the problem you encountered, in all likelihood. Let's discuss please.
> Fix issue #374

- eos/b-decays/observables.cc
- eos/form-factors/observables.cc
Fixes some latex representations
> Fix latex strings

- .github/workflows/macos-build+check.yaml
- python/eos/parameter.py
- python/eos/parameter_TEST.py
- depends on merging wilson-eft/wilson#71
- add test case
> Fix eos.Parameter.FromWCxf

- eos/constraint.cc
> Silence option override warning if the user is not overriding

- src/scripts/eos-analysis
> Use a common parser as parent parser in eos-analysis

- doc/api/python.rst.jinja
- examples/cli/btopilnu.plot
- python/eos/plot/plotter.py
Set default to 'linear' and rename old 'scale' option to 'scaling_factor'
Closes #435
> [python] Allow to set scales for the plot axes

- python/eos/analysis.py
> [python] fixed documentation of eos.Analysis.sample_pmc

- python/eos/analysis.py
> [python] Fix bug in manual constraints

- python/eos/analysis.py
- python/eos/parameter_TEST.py
- Correctly pass `kwargs` to `scipy.optimize.minimize`
- Conditionally skip a test case, since `wilson` is not a required dependency of EOS
> [python] Small changes

- doc/use-cases.rst
> [doc] Change 'kinematic' for 'variable' in the plots

- python/eos/plot/plotter.py
Enables further manipulation of the figure after creating a plot.
> [python] Return fig, ax

- python/eos/tasks.py
> [python] Fix overflowing ipywidget

- doc/faq.rst
* Describe how to use jupyter with venv
* Emphasize keywords to improve readability
> [doc] Use jupyter with venv

- examples/cli/btopilnu-find-mode.bash
- python/eos/data/native.py
- python/eos/tasks.py
- src/scripts/eos-analysis
> Fix the find_mode script and make it a task

- eos/observable.cc
- eos/observable.hh
- test/test.cc
> Ensure that inserted observables overwrite existing observables

- python/eos/plot/plotter.py
Added features to allow for option parsing in the `eos.plot.Plotter.Observable` and `eos.plot.Plotter.SignalPDF` classes.
> Parse the ``options`` key in ``eos.Plotter.{Observable,SignalPDF}``

- eos/observable.cc
> [eos] Fix the Warning message in the insertion of observables

- python/eos/analysis.py
- python/eos/data/native.py
- python/eos/tasks.py
- src/scripts/eos-analysis
Took the liberty to convert @fnovak42's commit into a PR.
> Added functions necessary for nested sampling

- eos/constraints/B-to-Kstar-ll.yaml
Remove double spaces and fixes #544
> Remove double spaces and fixes #544 

- doc/advanced.rst
- eos/observable.cc
- eos/observable_TEST.cc
- eos/utils/exception.cc
- eos/utils/exception.hh
- eos/utils/expression-cacher.hh
- eos/utils/expression-cloner.hh
- eos/utils/expression-evaluator.hh
- eos/utils/expression-fwd.hh
- eos/utils/expression-kinematic-reader.hh
- eos/utils/expression-maker.hh
- eos/utils/expression-observable.cc
- eos/utils/expression-parser-impl.hh
- eos/utils/expression-parser.hh
- eos/utils/expression-parser_TEST.cc
- eos/utils/expression-printer.hh
- eos/utils/expression-visitors.cc
- eos/utils/expression.hh
> [utils] Add kinematic variables to the expression parser

- eos/rare-b-decays/lambda-b-to-lambda1520-ll-base.cc
- eos/rare-b-decays/lambda-b-to-lambda1520-ll-base.hh
- eos/rare-b-decays/lambda-b-to-lambda1520-ll-naive.cc
- eos/rare-b-decays/lambda-b-to-lambda1520-ll-naive_TEST.cc
- eos/rare-b-decays/lambda-b-to-lambda1520-ll.cc
- eos/rare-b-decays/lambda-b-to-lambda1520-ll.hh
- eos/references.yaml
> Implement lepton masses in Lambda_b -> Lambda(1520)

- test/test.hh
> [test] update test.hh

- eos/b-decays/Makefile.am
- eos/b-decays/b-to-3l-nu.cc
- eos/b-decays/b-to-3l-nu.hh
- eos/b-decays/b-to-3l-nu_TEST.cc
- eos/b-decays/b-to-l-nu.hh
- eos/b-decays/observables.cc
- eos/form-factors/Makefile.am
- eos/form-factors/mesonic.cc
- eos/form-factors/mesonic.hh
- eos/form-factors/observables.cc
- eos/form-factors/parametric-kkvdz2022.cc
- eos/form-factors/parametric-kkvdz2022.hh
- eos/form-factors/parametric-kkvdz2022_TEST.cc
- eos/parameters/hadronic-matrix-elements.yaml
- eos/references.yaml
- eos/signal-pdf.cc
We started to implement the interface some time ago
> [form-factors] Add B->gamma^* form factors from [KKvDZ2022:A] and P->gamma^* interface

- python/eos/analysis.py
Comparison in if statement was changed from equality operator to `is`. For more information see: http://jaredgrubb.blogspot.com/2009/04/python-is-none-vs-none.html
> [python] Fix typo in optimize function in analysis.py

- .github/workflows/macos-build+check.yaml
- .github/workflows/manylinux-build+check+deploy.yaml
- .github/workflows/ubuntu-build+check+deploy.yaml
Update the actions to avoid warnings of deprecated commands in the workflows
> [github] Update all workflow actions to their latest version

- python/eos/plot/plotter.py
> Two fixes of eos.Plotter before the refactoring of the entire class

- eos/parameters/hadron-properties.yaml
> Fix bug in the LaTeX representations of some hadronic parameters

- .github/workflows/ubuntu-build+check+deploy.yaml
- doc/Makefile
- doc/doc_TEST.py
- eos/parameters/hadronic-matrix-elements.yaml
> Test latex representation of parameters

- .github/workflows/manylinux-build+check+deploy.yaml
- .github/workflows/ubuntu-build+check+deploy.yaml
- python/eos/data/native.py
Several errors in the eos.data.DynestyResults object were fixed:
- Loading the data for initialization was not set up properly
- A typo in the parameter description was fixed
- dynesty was not imported
> Errors in eos.data.DynestyResults

- eos/b-decays/b-to-gamma-l-nu.cc
- eos/b-decays/b-to-gamma-l-nu.hh
- eos/signal-pdf.cc
I am not sure about the definition of the cos theta_l variable. @pluegh Can you check it?
> [eos] Implement B -> gamma ell nu signal PDF

- python/eos/analysis.py
- python/eos/tasks.py
- src/scripts/eos-analysis
As discussed in issue #573, a seed was added to the rng used by the `DynamicNestedSampler`
> Add seed to nested sampling

- python/eos/plot/plotter.py
> [python] Fix false kde2d warning

- python/eos/plot/plotter.py
Provide users with the option to plot on a given axis:
```
fig, ax = plt.subplots(1,1)
plot_args = {
'axis': ax,
'plot': {
...
},
'contents': [
{
...
}
]
}
eos.plot.Plotter(plot_args).plot()
```
> [python] Add feature to enable plotting on given axis.

- python/eos/data/native.py
- python/eos/tasks.py
> [python] Bug and improvement in eos.tasks.find_mode

- python/eos/analysis.py
- python/eos/data/native.py
- python/eos/tasks.py
> Allow to initialize the ``find-mode`` task from previously obtained importance samples

- python/eos/plot/plotter.py
> [python] Provide the possibiltiy of plotting the graph of a function

- doc/defining-observables.rst
- eos/constraint.cc
Waiting for feedback from @cbolognani if this fixes the issue in her analysis.
> Respect begin/end slicing when creating a ``MultivariateGaussianBlock``

- python/_eos.cc
- python/eos/analysis_file.py
- python/eos/data/native.py
> Fix handling of options in `eos.data.Predictions`

- eos/form-factors/observables.cc
- eos/form-factors/parametric-bgjvd2019-impl.hh
- eos/form-factors/parametric-bgjvd2019.cc
- eos/form-factors/parametric-bgjvd2019.hh
- eos/references.yaml
Feature request by @juddharrison.
GitHub: resolves #649.
> Export B->D^(*) HQET form factors

- eos/form-factors/analytic-b-to-psd-dkmmo2008-impl.hh
- eos/form-factors/k-lcdas.hh
- eos/form-factors/pi-lcdas.hh
- eos/form-factors/psd-lcdas.hh
> Mark used parameters truly as used in B->P DKMMO:2008A form factors

- python/eos/tasks.py
> [python] Add option 'distribution' to corner plot

- .github/workflows/manylinux-build+check+deploy.yaml
- configure.ac
- doc/installation.rst
- python/setup.py.in
> [python] Remove support for Python 3.7 - issue #662

- eos/form-factors/parametric-kkvdz2022.cc
- eos/form-factors/parametric-kkvdz2022.hh
- eos/form-factors/parametric-kkvdz2022_TEST.cc
- eos/parameters/hadronic-matrix-elements.yaml
First try on adding the subtractions in kkvdz form factors.
ToDo:
> [form-factors] Add subtracted [KKvDZ:2022A] form factors

- eos/rare-b-decays/lambda-b-to-lambda-dilepton.cc
Thank you @dvandyk for finding the problem!
Closes #675
> [rare-b-decays] Fix the Lb -> L l l observables at large recoil

- python/eos/analysis_file.py
> [python] Allow for a list of kinematic assignements in the prediction task

- eos/b-decays/Makefile.am
- eos/b-decays/b-to-vec-nu-nu.cc
- eos/b-decays/observables.cc
- eos/rare-b-decays/Makefile.am
- eos/rare-b-decays/b-to-k-nu-nu_TEST.cc
- eos/rare-b-decays/b-to-kstar-nu-nu_TEST.cc
- eos/rare-b-decays/b-to-psd-nu-nu.cc
- eos/rare-b-decays/b-to-psd-nu-nu.hh
- eos/rare-b-decays/b-to-vec-nu-nu.cc
- eos/rare-b-decays/b-to-vec-nu-nu.hh
- eos/rare-b-decays/lambda-b-to-lambda-nu-nu-impl.hh
- eos/rare-b-decays/lambda-b-to-lambda-nu-nu.cc
- eos/rare-b-decays/lambda-b-to-lambda-nu-nu.hh
- eos/rare-b-decays/observables.cc
This PR:
- Moves the b -> s nu nu implementation to `eos/rare-b-decays`
- Implements B_s -> phi nu nu and Lambda_b -> Lambda nu nu
- Corrects small typos in the unit of some BR
> Some work on the bsnunu observables

- doc/Makefile
- doc/conf.py
- doc/constraints.rst.jinja
- doc/constraints.rst.py
- doc/parameters.rst.jinja
- doc/parameters.rst.py
- doc/references.rst.jinja
- doc/references.rst.py
- eos/parameters/sm-and-eft.yaml
> Use jinja to generate list of constraints, parameters, and references

- doc/api/python.rst.jinja
- doc/api/python.rst.py
> [doc] Document eos.tasks functions automatically

- examples/predictions.ipynb
> Remove rogue markup from notebook

- doc/installation.rst
> Add venv link to install instructions

- doc/constraints.rst.jinja
> Change the heading of the constraint table

- eos/form-factors/analytic-b-to-gamma-qcdf.cc
- eos/form-factors/analytic-b-to-gamma-qcdf.hh
- eos/parameters/hadron-properties.yaml
This PR includes changes related to B to gamma ell nu form factors. This includes minor bug fixes and the option to select various individual/partial contributions in addition to the entire sum.
> Changes for B to gamma ell nu

- examples/basics.ipynb
- examples/inference.ipynb
- examples/predictions.ipynb
> Solves issue 714 and 715

- python/eos/plot/plotter.py
> Add documentation for the rescale-by-width plot option

- doc/installation.rst
> Install instruction improvements

- eos/b-decays/b-to-3l-nu.cc
- eos/b-decays/b-to-3l-nu.hh
- eos/b-decays/b-to-3l-nu_TEST.cc
> Check physical phase space in B->3lnu observables

- eos/b-decays/b-to-psd-l-nu.cc
- eos/b-decays/b-to-psd-l-nu.hh
- eos/b-decays/observables.cc
I have added a function for `d^2BR/dq2/dcos(theta_l)` for b->psd-l-nu.
Also, I have added two related observables
- `B->pilnu::d^2BR/dq2/dcos(theta_l)`
- `B->Dlnu::d^2BR/dq2/dcos(theta_l)`
This is related, but does not solve, issue #731.
> Add double differential BR for b->psd-l-nu (issue #731)

- python/eos/plot/plotter.py
> Update documentation for Observable plotter

- eos/rare-b-decays/b-to-vec-nu-nu.cc
Extend the b-to-vec-nu-nu differential decay width for the scalar and tensor sector, as in eq. 13 of https://arxiv.org/pdf/2111.04327.pdf
> [rare-b-decays] implement scalar and tensor sectors for b-to-vec-nu-nu

- doc/Makefile
- doc/index.rst
- doc/signal-pdfs.rst.jinja
- doc/signal-pdfs.rst.py
- eos/Makefile.am
- eos/b-decays/Makefile.am
- eos/b-decays/signal-pdfs.cc
- eos/b-decays/signal-pdfs.hh
- eos/rare-b-decays/Makefile.am
- eos/rare-b-decays/signal-pdfs.cc
- eos/rare-b-decays/signal-pdfs.hh
- eos/signal-pdf-fwd.hh
- eos/signal-pdf-impl.hh
- eos/signal-pdf.cc
- eos/signal-pdf.hh
- eos/signal-pdf_TEST.cc
- python/_eos.cc
- python/eos/signal_pdf.py
- src/clients/eos-list-signal-pdfs.cc
- refactors the ``SignalPDFs`` code to reflect what we have been doing for ``Observables`` (#610)
- add list of known signal PDFs to the documentation (#733)
- handle non-existing PDFs gracefully in the factory method (#748)
> Fix three issues related to signal PDFs

- python/eos/observable.py
- python/eos/signal_pdf.py
Also rearrange/pyugrade code in the displaying of ``eos.Observables``.
> Enable interactive filter when displaying ``eos.SignalPDFs``

- eos/rare-b-decays/b-to-psd-nu-nu.cc
- eos/rare-b-decays/b-to-vec-nu-nu.cc
Set the differential branching fraction of B -> M nu nu to zero outside the physical range
> B -> K^(*) nu nu fix

- .github/workflows/pre-commit.yaml
- .pre-commit-config.yaml
- doc/installation.rst
> Add new workflow running pre-commit checks

- .github/actions/report-activity/index.js
- .github/actions/report-activity/template.md
- .github/workflows/weekly-builds.yaml
> Improve two workflows

- doc/installation.rst
- eos/statistics/log-likelihood.cc
- eos/statistics/test-statistic-impl.hh
- eos/statistics/test-statistic.cc
- python/_eos.cc
- python/eos/ipython.py
- python/eos/tasks.py
Resolves issues #832, #836, and #837.
> Miscellaneous changes

- .github/workflows/report-activity.yaml
- .github/workflows/weekly-builds.yaml
> Moves up weekly build and reports to earlier in the morning

- eos/maths/lagrange-polynomial.hh
- eos/maths/lagrange-polynomial_TEST.cc
- eos/nonlocal-form-factors/nonlocal-formfactors-p-to-p.cc
- eos/nonlocal-form-factors/nonlocal-formfactors-p-to-p_TEST.cc
- eos/nonlocal-form-factors/nonlocal-formfactors-p-to-v.cc
The error was added after the publication of the nonlocal paper. A test case is added to ensure that this doesn't happen again...
> Fix the nonlocal dispersive bounds

- src/scripts/eos-analysis
> [src] Fix the wrong dash in find-mode

- eos/utils/log.hh
- python/_eos.cc
- python/eos/__init__.py
- python/eos/analysis.py
- python/eos/analysis_file.py
- python/eos/datasets.py
- python/eos/tasks.py
- src/scripts/eos-analysis
The output can now look as follows at verbosity level 4
while at verbosity level 3 we see
> Start using fine-grained log levels and pretty up ``eos-analysis`` output

- eos/utils/log.cc
- eos/utils/log_TEST.cc
> Properly account for the new log levels in the C++ side

- .github/workflows/pypi-build+check+deploy.yaml
- .github/workflows/ubuntu-build+check+deploy.yaml
- doc/installation.rst
- python/setup.py.in
- src/scripts/eos-analysis
Steps to enable bash completion:
```
pip install argcomplete # outside all virtual environments!
activate-global-python-argcomplete --user
```
> Use ``argcomplete`` to provide bash completion for ``eos-analysis``

- doc/installation.rst
- eos/maths/Makefile.am
- eos/maths/legendre-polynomial-vector.hh
- eos/maths/legendre-polynomial-vector_TEST.cc
- eos/references.yaml
- eos/utils/Makefile.am
- eos/utils/omnes-factor-impl.hh
- eos/utils/omnes-factor.hh
- eos/utils/omnes-factor_TEST.cc
This is an implementation of B. Moussallams algorithm (https://arxiv.org/abs/hep-ph/9909292) to solve the integral
equation for single-channel Omnes factors.
The idea is to use it in future to implement, e.g., the pi-pi p-Wave Omnes factor etc.
> Single-Channel Omnes factor

- .github/workflows/pypi-build+check+deploy.yaml
- eos/form-factors/analytic-b-to-p-lcsr-impl.hh
- eos/form-factors/analytic-b-to-v-lcsr-impl.hh
- eos/nonlocal-form-factors/charm-loops-analytic-F279b-helper.cc
- eos/nonlocal-form-factors/charm-loops-analytic-F279d-helper.cc
- eos/nonlocal-form-factors/charm-loops-analytic-F27b.cc
- eos/nonlocal-form-factors/charm-loops-analytic-F27d-helper.cc
- eos/nonlocal-form-factors/charm-loops-analytic-F27d.cc
- eos/nonlocal-form-factors/charm-loops-analytic-F29b.cc
- eos/nonlocal-form-factors/charm-loops-analytic-F29d-helper.cc
- eos/nonlocal-form-factors/charm-loops-analytic-F29d.cc
- eos/nonlocal-form-factors/charm-loops-analytic-weight4w4w5w7.cc
- eos/nonlocal-form-factors/charm-loops-analytic-weight4wx3wx4.cc
- eos/nonlocal-form-factors/charm-loops-analytic.cc
> Changes for master

- src/scripts/eos-analysis
This fixes the remaining issues in issue #905
> Update documentation for sample-mcmc and find-modes for clarity

- python/eos/analysis_file.py
> Improve error message, fix bug

- examples/analysis-organisation.ipynb
- examples/b-to-u-l-nu.yaml
- python/eos/analysis_file.py
> Extend `analysis-organisation` examples notebook and some small modifications to the `AnalysisFile` class

- eos/statistics/log-likelihood.cc
> [statistics] Add a test-statistic for uniform bounds

- eos/rare-b-decays/b-to-ll.cc
- eos/rare-b-decays/b-to-ll_TEST.cc
> [rare-b-decays] Remove ill-defined B_d -> ll decays

- src/scripts/eos-analysis
> Fix default value for ``--end-index`` in ``predict-observables`` subcommand

- eos/form-factors/parametric-bsz2015-impl.hh
- python/_eos.cc
- python/eos/analysis.py
- src/scripts/eos-analysis
Fixes for #949, #934, and #931
> Various small fixes

- examples/b-to-u-l-nu.yaml
- python/Makefile.am
- python/eos/analysis_file_TEST.d/valid-analysis-file.yaml
- python/eos/analysis_file_TEST.py
- python/eos/analysis_file_description.py
- python/eos/tasks.py
- src/scripts/eos-analysis
- src/scripts/eos-analysis_TEST
- src/scripts/eos-analysis_TEST.d/analysis.yaml
This is the EOS side of changes. An example of a snakemake file utilizing the new tasks has been posted on the Discord server and will be merged into the analysis template repository.
> Add infrastructure to run reproducible analyses with Snakemake

- python/eos/plot/plotter.py
A fix for #903 - I've tried it quickly, see below
> Improves uncertainty band plotting

- python/eos/analysis_file.py
> Make eos compatible with python version 3.12

- doc/faq.rst
- doc/installation.rst.in
- doc/reference/analysis-file-format.rst
- doc/reference/command-line-interface.rst
- doc/reference/physics-conventions.rst
- python/eos_TEST.py
This closes #938, #953, #954 and #956.
> Improvement to the documentation

- eos/form-factors/observables.cc
Export all BGL coefficients in terms of IW functions as observables (for some reason not all of them were exported as observables)
> Export all BGL coefficients in terms of IW functions as observables

- configure.ac
- eos/Makefile.am
- eos/models/ckm.cc
- eos/models/ckm.hh
- eos/models/model.hh
- eos/models/standard-model.cc
- eos/models/standard-model.hh
- eos/models/standard-model_TEST.cc
- eos/models/wet.cc
- eos/models/wet.hh
- eos/models/wilson-coefficients.hh
- eos/parameters/hadron-properties.yaml
- eos/parameters/sm-and-eft.yaml
- eos/references.yaml
- eos/s-decays/Makefile.am
- eos/s-decays/k-to-l-nu.cc
- eos/s-decays/k-to-l-nu.hh
- eos/s-decays/k-to-l-nu_TEST.cc
- eos/s-decays/observables.cc
- eos/s-decays/observables.hh
> Implement leptonic kaon decay

- python/eos/analysis_file.py
> Turn an inexistant eos.Exception to a RuntimeError

- eos/b-decays/b-to-psd-psd.cc
- eos/form-factors/heavy-meson-lcdas-flvd2022.cc
- eos/reference_TEST.cc
- eos/statistics/log-posterior_TEST.cc
- eos/utils/cacheable_observable_TEST.cc
- eos/utils/expression-parser.hh
This PR silences a couple of warnings, including another one concerning a boost header that will be moved in future releases.
> Silence warnings

- eos/form-factors/Makefile.am
- eos/form-factors/mesonic-processes.hh
- eos/form-factors/mesonic.cc
- eos/form-factors/mesonic.hh
- eos/form-factors/observables.cc
- eos/form-factors/parametric-kkrvd2024.cc
- eos/form-factors/parametric-kkrvd2024.hh
- eos/form-factors/parametric-ksvd2025.cc
- eos/form-factors/parametric-ksvd2025.hh
- eos/form-factors/parametric-ksvd2025_TEST.cc
- eos/parameters/hadronic-matrix-elements.yaml
Working code, but potentially in need of some tidying
> Implementation of 0->Kpi form factors

- python/eos/analysis.py
- python/eos/analysis_TEST.py
> [python] Fix and test the miniter option of the sample_nested task

- eos/form-factors/parametric-bgjvd2019.cc
- eos/form-factors/parametric-bgjvd2019.hh
- eos/form-factors/parametric-bgl1997.hh
- eos/form-factors/parametric-kkvdz2022.cc
- eos/form-factors/parametric-kkvdz2022.hh
- eos/form-factors/parametric-kkvdz2022_TEST.cc
- eos/rare-b-decays/b-to-kstar-ll-gp2004.cc
- eos/rare-b-decays/b-to-kstar-ll-gp2004.hh
- eos/rare-b-decays/b-to-kstar-ll-gp2004_TEST.cc
- eos/utils/destringify.hh
- eos/utils/options.cc
- eos/utils/options.hh
Closes #985.
I checked the use cases, and it seems that a more sophisticated option with min/max is not needed.
> Integer option

- eos/b-decays/b-to-psd-psd-l-nu-impl.hh
- eos/b-decays/b-to-psd-psd-l-nu.cc
Speed-up achieved by only computing angular integrals once.
Closes #1035
> Speed up B -> P P' l nu implementation

- eos/form-factors/parametric-hkvt2025-impl.hh
- eos/form-factors/parametric-hkvt2025.hh
> Make parametric-hkvt2025 use scattering classes properly.

- python/eos/analysis.py
- python/eos/tasks.py
> Documents the analysis optimization and adds a warning

- doc/.gitignore
- doc/reference/physics-conventions.rst.jinja
- doc/reference/physics-conventions.rst.py
- eos/parameters/hadron-properties.yaml
- eos/parameters/hadronic-matrix-elements.yaml
- eos/parameters/sm-and-eft.yaml
- eos/utils/units.cc
- eos/utils/units.hh
- python/_eos.cc
- python/eos_TEST.py
> Improve the documentation of units and fill the missing ones in the parameters

- doc/reference/python.rst.py
- examples/analysis-organisation.ipynb
- examples/b-to-u-l-nu.yaml
Add headers and description of steps key in `analysis-organisation.nb`, add extended example of `steps` to analysis file `b-to-u-l-nu.yaml`.
> [examples] Improve optinonal keys in analysis-organisation

- .gitignore
- doc/faq.rst
- doc/installation.rst.in
Updating FAQ and corresponding infrastructure. Addresses #1064
> Move recommended virtual enviroment location

- eos/rare-b-decays/Makefile.am
- eos/rare-b-decays/b-to-k-ll-base.hh
- eos/rare-b-decays/b-to-k-ll-gvdv2020.cc
- eos/rare-b-decays/b-to-k-ll-gvdv2020.hh
- eos/rare-b-decays/b-to-k-ll-naive.cc
- eos/rare-b-decays/b-to-k-ll-naive.hh
- eos/rare-b-decays/b-to-k-ll.cc
- eos/rare-b-decays/b-to-kstar-ll-base.hh
- eos/rare-b-decays/b-to-kstar-ll-gvdv2020.cc
- eos/rare-b-decays/b-to-kstar-ll-gvdv2020.hh
- eos/rare-b-decays/b-to-kstar-ll-naive.cc
- eos/rare-b-decays/b-to-kstar-ll-naive.hh
- eos/rare-b-decays/b-to-kstar-ll.cc
- eos/rare-b-decays/bs-to-phi-ll-base.hh
- eos/rare-b-decays/bs-to-phi-ll-gvdv2020.cc
- eos/rare-b-decays/bs-to-phi-ll-gvdv2020.hh
- eos/rare-b-decays/bs-to-phi-ll-naive.cc
- eos/rare-b-decays/bs-to-phi-ll-naive.hh
- eos/rare-b-decays/bs-to-phi-ll.cc
> Implement a ``Naive`` tag for b->sll decays

- eos/observable.cc
- eos/observable.hh
- examples/external-observable.ipynb
- python/Makefile.am
- python/_eos.cc
- python/_eos/external-observable.cc
- python/_eos/external-observable.hh
- python/eos/figure/item.py
- d381d758490f353f99805eecde3867a0fddaa918 Fix a memory leek by adding the virtual destructor to the ``Observable`` base class.
- d2372ec2c4f6e4af8fbe5b44ff857efc28c401b2 Create a new class ``ExternalObservable`` (and companion ``ExternalObservableEntry``) that are used internally by the new Python function ``eos.register_python_observable``.
- d826a2828b9d8bfbb5dd091cabf38ca26b253ee2 Add a new item type to ``eos.figure`` to support plotting observables in the complex plan.
> Support writing observables in Python and plotting observables in the complex plane
